### ISSUE TITLE
[Dinobot4K] Can't boot to Setup Wizard on First Boot Up

### ISSUE THREAD

**Issue by budiarno** [PLi-metas/pli-extras#8]
Can't confirm whether the new update for dinobot 4k rc_models can solve my previous error on the remote control. It's just one more error on the first boot now, the E2 is in boot loop with this crashlog:

> policy2 in setting-->letterbox
> videomode_60hz-->720p50
> aspect in setting-->16:9
> policy in setting-->panscan
> policy2 in setting-->letterbox
> Traceback (most recent call last):
>   File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 52, in readPluginList
>   File "/usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/plugin.py", line 5, in <module>
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerwidget.py", line 35, in <module>
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvconfigmenu.py", line 13, in <module>
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/iptvupdate/updatemainwindow.py", line 14, in <module>
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/iptvupdate/iptvlist.py", line 11, in <module>
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/iptvdm/iptvdh.py", line 14, in <module>
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/libs/pCommon.py", line 7, in <module>
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerinit.py", line 43, in <module>
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerinit.py", line 34, in localeInit
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/tools/iptvtools.py", line 478, in printDBG
>   File "/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/tools/iptvtools.py", line 470, in getDebugMode
> IOError: [Errno 2] No such file or directory: '/etc/enigma2/settings'
> libpng warning: iCCP: known incorrect sRGB profile
> found 1 tuner
> found 2 tuner

**Comment by persianpros** [comment]
Ok compile and test again.

**Comment by persianpros** [comment]
Then I have to add dinobot's dedicated showiframe I guess ...

**Comment by budiarno** [comment]
Thank you, I'll wait.

**Comment by persianpros** [comment]
Done.

**Comment by budiarno** [comment]
Still bootloop. Here's the serial debug:

```
Booting Linux on physical CPU 0x0
Linux version 4.4.35 (oe-user@oe-host) (gcc version 6.3.0 (GCC) ) #1 SMP Tue May 15 04:04:34 WIB 2018
CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
initmrd: found no initmrd.
Machine model: Hisilicon
cma: Reserved 48 MiB at 0x38400000
cma: Reserved 4 MiB at 0x3c400000
Memory policy: Data cache writealloc
DT missing boot CPU MPIDR[23:0], fall back to default cpu_logical_map
PERCPU: Embedded 13 pages/cpu @dfc1d000 s22604 r8192 d22452 u53248
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 247032
Kernel command line: console=ttyAMA0,115200 root=/dev/mmcblk1p1 rootfstype=ext4 rootwait  blkdevparts=mmcblk0:1M(fastboot),1M(bootarM
log_buf_len individual max cpu contribution: 4096 bytes
log_buf_len total cpu_extra contributions: 12288 bytes
log_buf_len min size: 16384 bytes
log_buf_len: 32768 bytes
early log buf free: 14312(87%)
PID hash table entries: 2048 (order: 1, 8192 bytes)
Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
Memory: 899036K/992256K available (11461K kernel code, 1798K rwdata, 3444K rodata, 592K init, 2983K bss, 39972K reserved, 53248K cma)
Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
    vmalloc : 0xe0800000 - 0xff800000   ( 496 MB)
    lowmem  : 0xc0000000 - 0xe0400000   ( 516 MB)
    pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
    modules : 0xbf000000 - 0xbfe00000   (  14 MB)
      .text : 0xc0008000 - 0xc0b39894   (11463 kB)
      .init : 0xc0f7e000 - 0xc1012000   ( 592 kB)
      .data : 0xc1012000 - 0xc11d3898   (1799 kB)
       .bss : 0xc11d5000 - 0xc14befe8   (2984 kB)
SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
Hierarchical RCU implementation.
        Build-time adjustment of leaf fanout to 32.
NR_IRQS:352
clocksource: hisp804: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
sched_clock: 32 bits at 24MHz, resolution 41ns, wraps every 89478484971ns
Console: colour dummy device 80x30
Calibrating delay loop... 3170.30 BogoMIPS (lpj=1585152)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
CPU: Testing write buffer coherency: ok
ftrace: allocating 40288 entries in 119 pages
CPU0: update cpu_capacity 1024
CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
Setting up static identity map for 0x8280 - 0x82d8
CPU: hi3798mv200
CPU1: update cpu_capacity 1024
CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
CPU2: update cpu_capacity 1024
CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
CPU3: update cpu_capacity 1024
CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
Brought up 4 CPUs
SMP: Total of 4 processors activated (12681.21 BogoMIPS).
CPU: All CPU(s) started in SVC mode.
CPU3: update max cpu_capacity 1024
devtmpfs: initialized
VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275000 ns
NET: Registered protocol family 16
CPU3: update max cpu_capacity 1024
DMA: preallocated 2048 KiB pool for atomic coherent allocations
hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
hw-breakpoint: maximum watchpoint size is 8 bytes.
Serial: AMBA PL011 UART driver
f8b00000.uart: ttyAMA0 at MMIO 0xf8b00000 (irq = 21, base_baud = 0) is a PL011 rev2
console [ttyAMA0] enabled
f8b02000.uart: ttyAMA1 at MMIO 0xf8b02000 (irq = 22, base_baud = 0) is a PL011 rev2
f8b03000.uart: ttyAMA2 at MMIO 0xf8b03000 (irq = 23, base_baud = 0) is a PL011 rev2
pl061_gpio f8b20000.gpio0: PL061 GPIO chip @0xf8b20000 registered
pl061_gpio f8b21000.gpio1: PL061 GPIO chip @0xf8b21000 registered
pl061_gpio f8b22000.gpio2: PL061 GPIO chip @0xf8b22000 registered
pl061_gpio f8b23000.gpio3: PL061 GPIO chip @0xf8b23000 registered
pl061_gpio f8b24000.gpio4: PL061 GPIO chip @0xf8b24000 registered
pl061_gpio f8004000.gpio5: PL061 GPIO chip @0xf8004000 registered
pl061_gpio f8b26000.gpio6: PL061 GPIO chip @0xf8b26000 registered
pl061_gpio f8b27000.gpio7: PL061 GPIO chip @0xf8b27000 registered
pl061_gpio f8b28000.gpio8: PL061 GPIO chip @0xf8b28000 registered
pl061_gpio f8b29000.gpio9: PL061 GPIO chip @0xf8b29000 registered
hisilicon-pcie: probe of f0001000.pcie failed with error -1
hisi_iommu_ptable_addr:phy 0x1e800000    size:0x400000
hisi_iommu_err_rdaddr :phy 0x1ec59000    size:0x200
hisi_iommu_err_wraddr :phy 0x1ec59200     size:0x200
in hisi_iommu_domain_init start 
in hisi_iommu_domain_init end 
vgaarb: loaded
SCSI subsystem initialized
ssp-pl022 f8b1a000.spi: ARM PL022 driver, device ID: 0x00041022
ssp-pl022 f8b1a000.spi: mapped registers from 0xf8b1a000 to f9b1a000
spi_master spi0: will run message pump with realtime priority
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
media: Linux media interface: v0.10
Linux video capture interface: v2.00
Advanced Linux Sound Architecture Driver Initialized.
Bluetooth: Core ver 2.21
NET: Registered protocol family 31
Bluetooth: HCI device and connection manager initialized
Bluetooth: HCI socket layer initialized
Bluetooth: L2CAP socket layer initialized
Bluetooth: SCO socket layer initialized
clocksource: Switched to clocksource hisp804
FS-Cache: Loaded
NET: Registered protocol family 2
TCP established hash table entries: 4096 (order: 2, 16384 bytes)
TCP bind hash table entries: 4096 (order: 3, 32768 bytes)
TCP: Hash tables configured (established 4096 bind 4096)
UDP hash table entries: 256 (order: 1, 8192 bytes)
UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
NET: Registered protocol family 1
RPC: Registered named UNIX socket transport module.
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
NetWinder Floating Point Emulator V0.97 (double precision)
futex hash table entries: 1024 (order: 4, 65536 bytes)
squashfs: version 4.0 (2009/01/31) Phillip Lougher
NFS: Registering the id_resolver key type
Key type id_resolver registered
Key type id_legacy registered
nfs4filelayout_init: NFSv4 File Layout Driver Registering...
Installing knfsd (copyright (C) 1996 okir@monad.swb.de).
FS-Cache: Netfs 'cifs' registered for caching
jffs2: version 2.2. (NAND) �۩ 2001-2006 Red Hat, Inc.
fuse init (API version 7.23)
bounce: pool size: 64 pages
Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
io scheduler noop registered
io scheduler deadline registered (default)
io scheduler cfq registered
hiahci-phy: registered new sata phy driver
virtual device initialization.
brd: module loaded
loop: module loaded
hifmc100: registerd new interface driver hifmc100.
hifmc100: Found flash memory controller hifmc100.
hifmc100: no found spi-nor device.
hifmc100: no found nand device.
hifmc100: no found spi-nand device.
FEPHY:addr=2, la_am=0xe, ldo_am=0x3, r_tuning=0x18
libphy: himii: probed
hieth: attached port 0 PHY 2 to driver Generic PHY
PPP generic driver version 2.4.2
PPP BSD Compression module registered
PPP Deflate Compression module registered
usbcore: registered new interface driver asix
usbcore: registered new interface driver ax88179_178a
usbcore: registered new interface driver cdc_ether
usbcore: registered new interface driver dm9601
usbcore: registered new interface driver net1080
usbcore: registered new interface driver cdc_subset
usbcore: registered new interface driver zaurus
usbcore: registered new interface driver cdc_ncm
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ehci-pci: EHCI PCI platform driver
ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
ohci-pci: OHCI PCI platform driver
usbcore: registered new interface driver uas
usbcore: registered new interface driver usb-storage
usbcore: registered new interface driver usbserial
usbcore: registered new interface driver usbserial_generic
usbserial: USB Serial support registered for generic
mousedev: PS/2 mouse device common for all mice
i2c /dev entries driver
usbcore: registered new interface driver uvcvideo
USB Video Class driver (1.1.1)
sp805-wdt f8a2c000.watchdog: registration successful
usbcore: registered new interface driver btusb
registered new interface driver himciv300
mmc0: MAN_BKOPS_EN bit is not set
mmc0: new DDR MMC card at address 0001
mmcblk0: mmc0:0001 NCard  7.30 GiB 
mmcblk0boot0: mmc0:0001 NCard  partition 1 4.00 MiB
mmcblk0boot1: mmc0:0001 NCard  partition 2 4.00 MiB
mmcblk0rpmb: mmc0:0001 NCard  partition 3 128 KiB
 mmcblk0: p1(fastboot) p2(bootargs) p3(recovery) p4(deviceinfo) p5(baseparam) p6(pqparam) p7(logo) p8(logobak) p9(fastplay) p10(kern)
f9c40000.himciv200.SD: eMMC/MMC/SD Device NOT detected!
usbcore: registered new interface driver usbhid
usbhid: USB HID core driver
ashmem: initialized
usbcore: registered new interface driver snd-usb-audio
oprofile: no performance counters
oprofile: using timer interrupt.
Netfilter messages via NETLINK v0.30.
nfnl_acct: registering with nfnetlink.
ip_tables: (C) 2000-2006 Netfilter Core Team
arp_tables: (C) 2002 David S. Miller
NET: Registered protocol family 10
NET: Registered protocol family 17
Bluetooth: RFCOMM TTY layer initialized
Bluetooth: RFCOMM socket layer initialized
Bluetooth: RFCOMM ver 1.11
Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Bluetooth: BNEP filters: protocol multicast
Bluetooth: BNEP socket layer initialized
Bluetooth: HIDP (Human Interface Emulation) ver 1.2
Bluetooth: HIDP socket layer initialized
Key type dns_resolver registered
Registering SWP/SWPB emulation handler
mmc1: Problem switching card into high-speed mode!
mmc1: new SDHC card at address 0001
mmcblk1: mmc1:0001 00000 7.45 GiB 
 mmcblk1: p1 p2
sec os HAL_Cipher_EnableMmu...
hisi-sndcard hisi-sndcard: aiao-hifi <-> hisi-i2s mapping ok
ALSA device list:
  #0: HISI-AIAO
EXT4-fs (mmcblk1p1): mounted filesystem with ordered data mode. Opts: (null)
VFS: Mounted root (ext4 filesystem) on device 179:33.
devtmpfs: mounted
Freeing unused kernel memory: 592K (c0f7e000 - c1012000)
This architecture does not have kernel memory protection.
INIT: version 2.88 booting
EXT4-fs (mmcblk1p2): mounted filesystem with ordered data mode. Opts: (null)
SVB: type = 2, core vmin 870mv
Mali: Mali device driver loaded
misc hi_dbe: hi_dbe ready
Load hi_tuner.ko success.       (SDK_VERSION:[HiSTBLinuxV100R005C00SPC042_20170312] Build Time:[Mar 28 2018, 12:00:19])
Smartcard driver (sci)
Version 4.00 (c) 2016-2017 Honza Petrous
scifi: register /dev/sci0
Load hi_pmoc.ko success.        (SDK_VERSION:[HiSTBLinuxV100R005C00SPC042_20170312] Build Time:[Mar 28 2018, 12:01:59])
tntfs: module license 'Commercial. For support email ntfs-support@tuxera.com.' taints kernel.
Disabling lock debugging due to kernel taint
Tuxera NTFS driver 3016.7.1.2.3 [Flags: R/W MODULE].
Built against headers 4.4.35_hi3798mv2x #1 SMP Mon Feb 13 17:06:10 CST 2017 arm
Running on kernel 4.4.35 #1 SMP Tue May 15 04:04:34 WIB 2018 armv7l
WARNING: Running kernel does not match configured kernel headers the driver was built with!  The driver needs to be rebuilt with the!
DVB: registering new adapter (firedtv)
(NULL device *): DVB: registering adapter 0 frontend 0 (HISI 3136 DVB-S)...
[00:00:03:555 ERROR-HI_TUNER]:AVL68XX_Init[171]:Avl68xx{1,1,28}{24,8}
[00:00:03:561 ERROR-HI_TUNER]:Avl68xx_Initialize[131]:Avl68xx:Initialize{1,2}
random: nonblocking pool is initialized
[00:00:05:686 ERROR-HI_TUNER]:mxl608_init_tuner2[252]:!!!!!!MxL608T_Initialize{1-36000000}
[00:00:05:699 ERROR-HI_TUNER]:Avl68xx_Initialize[150]:Avl68xx::Tuner ok
[00:00:05:716 ERROR-HI_TUNER]:Avl68xx_Initialize[158]:Avl68xx::ok
[00:00:05:721 ERROR-HI_TUNER]:AVL68XX_Init[196]:Avl68xx:SUCCESS uiChipNo 1
(NULL device *): DVB: registering adapter 0 frontend 1 (AvLink DVBT2/C)...
fdtv_dvb_register success
input: dreambox advanced remote control (native) as /devices/virtual/input/input0
init_dboxdev success!!!!!!!!!
EXT4-fs (mmcblk1p1): re-mounted. Opts: data=ordered
/usr/bin/showiframe: error while loading shared libraries: libhi_common.so: cannot open shared object file: No such file or directory
ALSA: Restoring mixer settings...
vm.dirty_writeback_centisecs = 300
vm.dirty_background_ratio = 1
vm.dirty_ratio = 60
INIT: Entering runlevel: 3
No state is present for card HISIAIAO
[00:00:06:661 ERROR-HI_AO]:AO_SND_SetVolume[1485]:NULL pointer 

Hardware is initialized using a generic method
Configuring network interfaces... /usr/share/alsa/init/default:26: value write error: No such file or directory
No state is present for card HISIAIAO
IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
udhcpc: option -h NAME is deprecated, use -x hostname:NAME
udhcpc (v1.24.1) started
Sending discover...
hieth f9c30000.hieth eth0: Link is Up - 100Mbps/Full - flow control rx/tx
IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sending discover...
Sending discover...
No lease, forking to background
done.
Starting system message bus: dbus.
Starting Dropbear SSH server: Generating key, this may take a while...
Public key portion is:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC+IGusetPHGjNDvLV9W38NPEPRlmxJIC8kockLOJecLu+XsIsanBrLHlL/y6PoQdvqdv7RlZe9h2x1uf7hiWeW9iFr55+mk
Fingerprint: md5 76:a5:58:f8:08:7c:16:61:67:80:b0:f5:5e:46:11:50
dropbear.
Starting rpcbind daemon...done.
Mounting remote filesystems...
starting statd: done
Starting internet superserver: inetd.
Starting Samba: smbd nmbd wsdd.
Starting syslogd/klogd: done
 * Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon
   ...done.
/usr/bin/showiframe: error while loading shared libraries: libhi_common.so: cannot open shared object file: No such file or directory
PYTHONPATH: /usr/lib/enigma2/python
DVB_API_VERSION 5 DVB_API_VERSION_MINOR 10
ENIGMA_DEBUG_LVL=3
dbox_oled_ioctl 4117
dvbs_set_tone 1
dvbs_set_voltage: ??
dvbs_set_tone 1
dvbs_set_voltage: ??
dvbs_set_voltage: ??
[MAIN] executing main
no profile data available
found 1 tuner
found 2 tuner
aspect in setting-->any
policy in setting-->bestfit
aspect in setting-->16:9
policy in setting-->panscan
policy2 in setting-->letterbox
aspect in setting-->16:9
policy in setting-->panscan
policy2 in setting-->letterbox
aspect in setting-->16:9
policy in setting-->panscan
policy2 in setting-->letterbox
aspect in setting-->16:9
policy in setting-->panscan
policy2 in setting-->letterbox
videomode_60hz-->720p50
aspect in setting-->16:9
policy in setting-->panscan
policy2 in setting-->letterbox
libpng warning: iCCP: known incorrect sRGB profile
found 1 tuner
found 2 tuner
Backtrace:
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x6B8B8]
/lib/libc.so.6(__default_rt_sa_restorer) [0xB61B7C60]
-------FATAL SIGNAL
Backtrace:
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x6B8B8]
/lib/libc.so.6(__default_rt_sa_restorer) [0xB61B7C60]
-------FATAL SIGNAL
Backtrace:
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x6B8B8]
/lib/libc.so.6(__default_rt_sa_restorer) [0xB61B7C60]
-------FATAL SIGNAL
Backtrace:
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x6B8B8]
/lib/libc.so.6(__default_rt_sa_restorer) [0xB61B7C60]
-------FATAL SIGNAL
Backtrace:
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x6B8B8]
/lib/libc.so.6(__default_rt_sa_restorer) [0xB61B7C60]
-------FATAL SIGNAL
Backtrace:
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x6B8B8]
/lib/libc.so.6(__default_rt_sa_restorer) [0xB61B7C60]
-------FATAL SIGNAL
Backtrace:
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x6B8B8]
/lib/libc.so.6(__default_rt_sa_restorer) [0xB61B7C60]
-------FATAL SIGNAL
Backtrace:
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x6B8B8]
/lib/libc.so.6(__default_rt_sa_restorer) [0xB61B7C60]
-------FATAL SIGNAL
```

Sorry a bit longer this time. But I spot this line on the log:

`/usr/bin/showiframe: error while loading shared libraries: libhi_common.so: cannot open shared object file: No such file or directory`

**Comment by budiarno** [comment]
I suspect we need the libraries. Their libraries are also close source anyway.

**Comment by persianpros** [comment]
Ok test again now, I did add dinobot-libs
